"""End-to-end exit gate: the recorded weather agent replays offline.

These tests never touch the network or need an API key - they replay the
committed golden cassette (regenerated by ``examples/record_weather.py``).
"""

from pathlib import Path
from typing import Any

import pytest
from weather_agent import MODEL, run_agent

from reenact.record import hash_request, redact
from reenact.replay import DivergenceError, replaying
from reenact.schema import LLMCallEvent
from reenact.store import load_cassette, save_cassette

GOLDEN = Path(__file__).resolve().parents[1] / "examples" / "golden" / "weather.json"


class _OfflineClient:
    """A client whose network path raises - proof that replay never calls out."""

    class _Messages:
        def create(self, **kwargs: Any) -> Any:
            raise AssertionError("replay made a live API call")

    def __init__(self) -> None:
        self.messages = _OfflineClient._Messages()


def test_agent_replays_to_the_recorded_answer_offline() -> None:
    trajectory = load_cassette(GOLDEN)
    client = _OfflineClient()
    with replaying(client, trajectory):
        answer = run_agent(client)
    assert "cloudy" in answer.lower()  # the recorded Paris forecast


def test_recording_is_a_think_act_think_trajectory() -> None:
    trajectory = load_cassette(GOLDEN)
    types = [event.type for event in trajectory.events]
    assert types == ["llm_call", "tool_call", "llm_call"]


def test_changed_prompt_diverges() -> None:
    trajectory = load_cassette(GOLDEN)
    client = _OfflineClient()
    with replaying(client, trajectory), pytest.raises(DivergenceError):
        client.messages.create(
            model=MODEL,
            max_tokens=256,
            messages=[{"role": "user", "content": "somewhere else entirely"}],
        )


def test_golden_cassette_is_clean_and_self_consistent() -> None:
    # No secret leaked into a committed file, and every request hash still
    # recomputes from its stored (redacted) request.
    assert "sk-ant" not in GOLDEN.read_text(encoding="utf-8")
    trajectory = load_cassette(GOLDEN)
    for event in trajectory.events:
        if isinstance(event, LLMCallEvent):
            assert event.request_hash == hash_request(redact(event.request))


def test_golden_cassette_round_trips_byte_identical(tmp_path: Path) -> None:
    trajectory = load_cassette(GOLDEN)
    first = tmp_path / "first.json"
    second = tmp_path / "second.json"
    save_cassette(trajectory, first)
    save_cassette(load_cassette(first), second)
    assert first.read_bytes() == second.read_bytes()
