"""The M2 exit gate: >=100 real recordings replay offline, byte-identical.

These tests replay the committed corpus (regenerated by
``examples/record_corpus.py``); they never touch the network or need a key. The
recordings are real - captured against the live Anthropic API - so this is the
"record online -> kill network -> full instant replay" trick, generalized past
the single weather agent.
"""

from pathlib import Path
from typing import Any

import corpus_agents as agents
import pytest
import record_corpus as corpus
from typer.testing import CliRunner

from reenact.bench.determinism import measure_determinism
from reenact.cli import app
from reenact.replay import Clock, DivergenceError, load_clock, replaying
from reenact.store import load_cassette

CORPUS = Path(__file__).resolve().parents[1] / "examples" / "corpus"
SHAPES = {"qa", "tool_use", "parallel", "multistep", "timestamped"}


class _OfflineClient:
    """A client whose real network path raises - proof replay never calls out."""

    class _Messages:
        def create(self, **kwargs: Any) -> Any:
            raise AssertionError("replay made a live API call")

    def __init__(self) -> None:
        self.messages = _OfflineClient._Messages()


def _run_shape(shape: str, client: Any) -> str:
    if shape == "qa":
        return agents.qa(client, corpus.QUESTIONS[0])
    if shape == "tool_use":
        return agents.tool_use(client, corpus.CITIES[0])
    if shape == "parallel":
        return agents.parallel(client, corpus.CITY_SETS[0])
    if shape == "multistep":
        return agents.multistep(client, corpus.TOPICS[0])
    raise ValueError(shape)


def test_corpus_has_at_least_100_runs_across_five_shapes() -> None:
    cassettes = sorted(CORPUS.glob("*.json"))
    assert len(cassettes) >= 100
    assert {load_cassette(p).name for p in cassettes} == SHAPES


def test_determinism_bench_meets_the_floor() -> None:
    result = measure_determinism(CORPUS)
    assert result["total_runs"] >= 100
    assert result["within_floor"]  # overall pct >= 95
    # Segmented honestly: both sequential and parallel runs exist and clear the floor.
    segments = result["segments"]
    assert segments["parallel"]["total"] > 0
    assert segments["sequential"]["total"] > 0
    assert segments["parallel"]["pct"] >= 95.0
    assert segments["sequential"]["pct"] >= 95.0


@pytest.mark.parametrize("shape", ["qa", "tool_use", "parallel", "multistep"])
def test_each_shape_replays_offline(shape: str) -> None:
    # STRICT replay raises on any drift, so completing without a raise - and with
    # an empty divergence list - is the proof the run reproduced byte-identical.
    trajectory = load_cassette(CORPUS / f"{shape}-00.json")
    client = _OfflineClient()
    with replaying(client, trajectory) as player:
        answer = _run_shape(shape, client)
    assert isinstance(answer, str)
    assert not player.divergences


def test_timestamped_replays_only_with_the_clock_shim() -> None:
    trajectory = load_cassette(CORPUS / "timestamped-00.json")
    question = corpus.TS_QUESTIONS[0]

    # With the recorded clock, the timestamped prompt is rebuilt identically.
    client = _OfflineClient()
    with replaying(client, trajectory):
        agents.timestamped(client, load_clock(trajectory), question)

    # With a live clock, the prompt drifts and STRICT replay refuses - the shim
    # is what earns the byte-identical replay.
    other = _OfflineClient()
    with replaying(other, trajectory), pytest.raises(DivergenceError):
        agents.timestamped(other, Clock(), question)


def test_cli_replay_reports_clean_on_a_corpus_run() -> None:
    result = CliRunner().invoke(app, ["replay", str(CORPUS / "qa-00.json")])
    assert result.exit_code == 0
    assert "clean" in result.stdout
